domain: example.com
records:
  - name: '@'
    type: A
    content: 192.168.0.0
    proxy: true
  - name: www
    type: A
    content: 192.168.0.0
    proxy: true
  - name: info
    type: CNAME
    content: 192.168.0.0
    proxy: false
